apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: nvidia-gpu-addon-operator.v99.0.0
  namespace: placeholder
spec:
  relatedImages:
    - name: console-plugin
      image: quay.io/edge-infrastructure/console-plugin-nvidia-gpu@sha256:248080b389af7249389d6d29c6683127b92932f2d6439f7474b3886b08773860
